config/routes.rb
Rails.application.routes.draw do
  root :to => 'stories#index'
  get '/stories/images', to: 'stories#images'

  resources :stories do
    resources :contributions
  end
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  belongs_to :story

  validates :username, :presence => true
  validates :sentence, :presence => true
end

app/models/story.rb
class Story < ActiveRecord::Base
  has_many :contributions
  validates :title, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  def new
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new
    @contribution.image = "Animals/#{1+rand(15).ceil}.png"
  end

  def create
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.new(contribution_params)
    @contribution.image = params[:contribution][:image]
    if @contribution.save
      redirect_to story_path(@contribution.story)
    else
      render :new
    end
  end

  def show
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.find(params[:id])
  end

  def edit
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.find(params[:id])
  end

  def update
    @story = Story.find(params[:story_id])
    @contribution = @story.contributions.find(params[:id])
    if @contribution.update(contribution_params)
      redirect_to story_path(@story)
    else
      render :edit
    end
  end

  # add destroy action here

  private
    def contribution_params
      params.require(:contribution).permit(:username, :sentence)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all.order(created_at: :desc)
  end

  def new
    @story = Story.new
  end

  def show
    @story = Story.find(params[:id])
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      redirect_to stories_path
    else
      render :new
    end
  end

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to stories_path
    else
      render :edit
    end
  end

  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_path
  end

  def images
    @imagesAll = Dir.entries("app/assets/images/Animals")
    @images = @imagesAll.select{ |i| i[/\.png$/] }
  end

  private
  def story_params
    params.require(:story).permit(:title)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contributions/_form.html.erb
<div id="image">
  <%= image_tag(@contribution.image, height: 40) %>
</div>


<%= form_for [@story, @contribution] do |f| %>
  <%= f.label :username %>
  <p><%= f.text_field :username %></p>
  <p><%= f.text_area :sentence, cols: 100, rows: 2, maxlength: 140, placeholder: "Contribute to the story. Add Sentence here..." %>
  </p>
  <%= f.hidden_field :image, :value => @contribution.image %>
  <%= f.submit %>
<% end %>

app/views/contributions/edit.html.erb
<h1>Edit Contribution</h1>

<%= render 'form' %>

app/views/contributions/new.html.erb
<div class="container">
<h1>New Contribution</h1>

<%= render "form" %>
</div>

app/views/contributions/show.html.erb
<div class="container">
<h1> <%= @contribution.sentence %> </h1>

<%= image_tag("#{@contribution.image}", height: 40) %>

  <div id= "usercontent">
    <p><%= @contribution.username %></p>
  </div>
</div>

<div class="container">
<%= link_to 'edit sentence', edit_story_contribution_path(@story, @contribution)%>

<%= link_to 'delete sentence', story_contribution_path(@story, @contribution), :data => {:confirm => "Are you sure?", :method => "delete"} %>

<p><%= link_to "Return to Story", story_path(@story) %></p>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StoryTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/stories/_form.html.erb
<%= render 'layouts/errors', :object => @story %>

<%= form_for @story do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>

<%= render 'form' %>

app/views/stories/images.html.erb
  <% @images.each do |image| %>
    <%= image_tag("Animals/#{image}", height: 40) %>
  <% end %>

app/views/stories/index.html.erb
<div class = "container">
  <div class ="header">
  <h1>StoryTime</h1>
  </div>

  <div id="storylist">
    <ul>
      <% @stories.each do |story| %>
          <li><%= link_to story.title, story_path(story) %></li>
      <% end %>
    </ul>
  </div>

  <div id ="editlink">
    <%= link_to "Add Story", new_story_path %>
  </div>
  <div id ="imagelink">
    <%= link_to "Click Here to See All Images", stories_images_path %>
  </div>
</div>

app/views/stories/new.html.erb
<div class="container">
<h1>New Story</h1>

<%= render "form" %>
</div>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>
<%= link_to "Edit Story Title", edit_story_path(@story) %>

<div id="content">
<% if @story.contributions.any? %>
<% @story.contributions.each do |contribution| %>
  <%= link_to contribution.sentence, story_contribution_path(@story, contribution) %>
<% end %>
</div>

<% else %>
  <p>There have been no contributions to this story yet.  Please add a    contribution</p>
<% end %>
<p><%= link_to "Contribute to the story", new_story_contribution_path(@story) %></p>

<%= link_to "Delete Story", story_path(@story), :data => {:confirm => "Are you sure?", :method => "delete"} %>
<p><%= link_to "Return to Stories", stories_path %></p>